export default {
    fontDetails:{
        fontSize:12.5,
        color:"#707070"
    },
    fontDetailsBox:{
        fontSize:12.5,
        color:"#ffffff"
    },
    fontShowTime:{
        fontSize:15,
        color:"#ffffff"
    },
    fontOrderSpecifications:{
        fontSize:12.5,
        color:"#707070"
    },
    fontPrimaryOrderSpecs:{
        fontSize:22,
        color:"black"
    },
    fontOrderName:{
        color:"black",
        fontSize:17.5
    },
    fontOrderPrice:{
        color:"black",
        fontSize:17.5
    },
    fontOrderSpecs:{
        fontSize:10,
        color:"#707070"
    },
    fontOrderDetails:{
        fontSize:10,
        color:'black'
    },
    fontDiscountItem:{
        fontSize:12.5,
        color:'#ef4349',
      
    }

}